name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    name: Build
    env:
      SCHEME: "ContinuesIntegrationExp"
      DEVICE: "iPhone 11"
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build application
      run: |
            set -o pipefail && xcodebuild clean -scheme $SCHEME -destination "platform=iOS Simulator,name=$DEVICE" | xcpretty --color --simple
   
name: Feature pipeline

on: pull_request
